apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileless-malware-simulator
  labels:
    app: fileless-malware-simulator
spec:
  selector:
    matchLabels:
        app: fileless-malware-simulator
  replicas: 1 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fileless-malware-simulator
    spec:
      containers:
        - name: fileless-malware-simulator
          image: ${{secrets.ECR_REGISTRY}}/${{secrets.ECR_REPOSITORY}}:latest
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
